const {
  NEXT_PUBLIC_GQL_API_URL,
  NEXT_PUBLIC_GQL_WS_URL,
  GQL_ACCESS_TOKEN,
  GQL_ID_TOKEN,
  ISSUER_BASE,
  REALM_NAME,
  REALM_CLIENT_ID,
  REALM_CLIENT_SECRET,
} = process.env;

const ISSUER = `${ISSUER_BASE}${REALM_NAME}`;
const CLIENT_ID = REALM_CLIENT_ID;
const CLIENT_SECRET = REALM_CLIENT_SECRET;

const config = {
  GQL_API_URL: NEXT_PUBLIC_GQL_API_URL ?? "http://localhost:8080/graphql",
  GQL_WS_URL: NEXT_PUBLIC_GQL_WS_URL ?? "ws://localhost:8080/subscriptions",
  ISSUER: ISSUER ?? "",
  CLIENT_ID: CLIENT_ID ?? "",
  CLIENT_SECRET,
  REALM_NAME: REALM_NAME ?? "",
  REALM_CLIENT_SECRET: REALM_CLIENT_SECRET ?? "",
  REALM_CLIENT_ID: REALM_CLIENT_ID ?? "",
  GQL_ACCESS_TOKEN: GQL_ACCESS_TOKEN ?? "",
  GQL_ID_TOKEN: GQL_ID_TOKEN ?? "",
};

export default config;
